# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Web & Mobile Design - DMA 331 - Fall 2022
description: > # this means to ignore newlines until "baseurl:"
  Students use principles of visual and interaction design to create high-fidelity web and mobile application prototypes. The course covers wireframing, layout, typography, responsive media and design, animation, mobile-first design, frameworks. Students practice skills and principles needed to create front-end web and application designs.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://f22.dma331.rehanbutt.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

sass:
  style: compressed

future: true

collections:
  assignments:
    output: true
    permalink: /assignments/:path
  classes:
    output: true
    permalink: /classes/:path